/**
 * actionTypes 配置类
 * Created by Li Jian on 2017/01/30.
 */

//登录
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

//获取登录用户信息
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE'

//登出
export const LOGOUT = 'LOGOUT'

//重置提交标志
export const RESET_SUBMIT_FLAG = 'RESET_SUBMIT_FLAG'

//page,size改变
export const CHANGE_PAGE_SIZE = 'CHANGE_PAGE_SIZE'

//根据keyword获取用户列表
export const GET_USER_LIST_BY_KEYWORD_REQUEST = 'GET_USER_LIST_BY_KEYWORD_REQUEST'
export const GET_USER_LIST_BY_KEYWORD_SUCCESS = 'GET_USER_LIST_BY_KEYWORD_SUCCESS'
export const GET_USER_LIST_BY_KEYWORD_FAILURE = 'GET_USER_LIST_BY_KEYWORD_FAILURE'

//保存管理员
export const SAVE_ADMIN_REQUEST = 'SAVE_ADMIN_REQUEST'
export const SAVE_ADMIN_SUCCESS = 'SAVE_ADMIN_SUCCESS'
export const SAVE_ADMIN_FAILURE = 'SAVE_ADMIN_FAILURE'

//删除管理员
export const REMOVE_ADMIN_REQUEST = 'REMOVE_ADMIN_REQUEST'
export const REMOVE_ADMIN_SUCCESS = 'REMOVE_ADMIN_SUCCESS'
export const REMOVE_ADMIN_FAILURE = 'REMOVE_ADMIN_FAILURE'

//获取管理员列表
export const GET_ADMINS_REQUEST = 'GET_ADMINS_REQUEST'
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS'
export const GET_ADMINS_FAILURE = 'GET_ADMINS_FAILURE'

//保存考试配置信息
export const ADD_EXAM_REQUEST = 'ADD_EXAM_REQUEST'
export const ADD_EXAM_SUCCESS = 'ADD_EXAM_SUCCESS'
export const ADD_EXAM_FAILURE = 'ADD_EXAM_FAILURE'

//更新考试信息
export const UPD_EXAM_REQUEST = 'UPD_EXAM_REQUEST'
export const UPD_EXAM_SUCCESS = 'UPD_EXAM_SUCCESS'
export const UPD_EXAM_FAILURE = 'UPD_EXAM_FAILURE'

//更新考试样卷url信息
export const UPD_EXAM_SAMPLE_REQUEST = 'UPD_EXAM_SAMPLE_REQUEST'
export const UPD_EXAM_SAMPLE_SUCCESS = 'UPD_EXAM_SAMPLE_SUCCESS'
export const UPD_EXAM_SAMPLE_FAILURE = 'UPD_EXAM_SAMPLE_FAILURE'

//删除考试信息
export const DEL_EXAM_REQUEST = 'DEL_EXAM_REQUEST'
export const DEL_EXAM_SUCCESS = 'DEL_EXAM_SUCCESS'
export const DEL_EXAM_FAILURE = 'DEL_EXAM_FAILURE'

//获取考试列表
export const GET_EXAMS_REQUEST = 'GET_EXAMS_REQUEST'
export const GET_EXAMS_SUCCESS = 'GET_EXAMS_SUCCESS'
export const GET_EXAMS_FAILURE = 'GET_EXAMS_FAILURE'

//获取历史考试编号
export const GET_HISTORY_EXAM_CODE_REQUEST = 'GET_HISTORY_EXAM_CODE_REQUEST'
export const GET_HISTORY_EXAM_CODE_SUCCESS = 'GET_HISTORY_EXAM_CODE_SUCCESS'
export const GET_HISTORY_EXAM_CODE_FAILURE = 'GET_HISTORY_EXAM_CODE_FAILURE'

//编辑考试信息
export const EXAM_EDIT = 'EXAM_EDIT'

//获取考试列表用作tabs
export const GET_EXAM_TABS_REQUEST = 'GET_EXAM_TABS_REQUEST'
export const GET_EXAM_TABS_SUCCESS = 'GET_EXAM_TABS_SUCCESS'
export const GET_EXAM_TABS_FAILURE = 'GET_EXAM_TABS_FAILURE'

//根据考试编号获取试卷列表
export const GET_EXAM_PAPERS_REQUEST = 'GET_EXAM_PAPERS_REQUEST'
export const GET_EXAM_PAPERS_SUCCESS = 'GET_EXAM_PAPERS_SUCCESS'
export const GET_EXAM_PAPERS_FAILURE = 'GET_EXAM_PAPERS_FAILURE'
